name       : mono-addins
version    : 1.1
release    : 4
source     :
    - http://download.mono-project.com/sources/mono-addins/mono-addins-1.1.tar.gz : ab98baf5364b911a4e131b6bfe50305901fd68c3baa121e4ca7f5429c8875674
license    : GPL-2.0
component  : programming
summary    : Mono.Addins is a generic framework for creating extensible applications.
description: |
    Mono.Addins is a generic framework for creating extensible applications, and for creating add-ins which extend those applications. This framework has been designed to be useful for a wide range of applications: from simple applications with small extensibility needs, to complex applications which need support for large add-in structures.
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
setup      : |
    %configure MCS=/usr/bin/mcs--enable-gui-gtk3
build      : |
    %make
install    : |
    %make_install
